# Generated by Django 5.2.12 on 2026-03-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('church', models.CharField(max_length=100)),
                ('celphone', models.CharField(max_length=11)),
                ('emergency_contact', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('local_proof', models.CharField()),
                ('payment_status', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consent_given', models.CharField()),
                ('ip_address', models.CharField()),
            ],
        ),
    ]
