# Generated by Django 5.2.12 on 2026-05-14 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmailControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_id', models.IntegerField()),
                ('email_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LogReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levelname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('asctime', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('filename', models.CharField(max_length=100)),
                ('lineno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Igreja',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enrollments.distrito')),
            ],
        ),
        migrations.CreateModel(
            name='Inscricoes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=11, verbose_name='Whatsapp/celular')),
                ('funcao', models.CharField(choices=[('CLERIGO', 'Clérigo (Pastor/Missionária)'), ('MEMBRO', 'Membro')], verbose_name='Função')),
                ('quantidade_parcelas', models.IntegerField(default=1, verbose_name='Quantidade de parcelas (Vencimento todo dia 20).')),
                ('status_pagamento', models.CharField(choices=[('PENDENTE', 'PENDENTE'), ('CONFIRMADO', 'CONFIRMADO')], default='PENDENTE')),
                ('apto_concilio', models.CharField(choices=[('NAO', 'NÃO'), ('SIM', 'SIM')], verbose_name='Apto para o Concílio GERAL de 2027?')),
                ('possui_comorbidade', models.CharField(choices=[('NAO', 'NÃO'), ('SIM', 'SIM')], verbose_name='Possui alguma Comorbidade?')),
                ('qual_comorbidade', models.CharField(blank=True, max_length=100, verbose_name='Qual Comorbidade?')),
                ('pernoite', models.CharField(choices=[('NAO', 'NÃO'), ('SIM', 'SIM')], verbose_name='Você dormirá no acampamento Efraim?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consent_given', models.BooleanField(default=False)),
                ('ip_address', models.CharField(blank=True)),
                ('last_email', models.DateTimeField(blank=True, null=True)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enrollments.distrito')),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enrollments.igreja')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
            },
        ),
        migrations.CreateModel(
            name='Painel',
            fields=[
            ],
            options={
                'verbose_name_plural': 'DASHBOARD',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('enrollments.inscricoes',),
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inscricao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='enrollments.inscricoes')),
            ],
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observações', models.TextField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('PENDENTE', 'PENDENTE'), ('PAGA', 'PAGA')], default='PENDENTE')),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='enrollments.pagamento')),
            ],
        ),
    ]
