# Generated by Django 5.2.12 on 2026-08-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricoes',
            name='sexo',
            field=models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino')], default='MASCULINO', max_length=10),
        ),
        migrations.AlterField(
            model_name='inscricoes',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='CPF (Somente Números)'),
        ),
    ]
