# Generated by Django 5.2.12 on 2026-03-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='consent_given',
            field=models.BooleanField(default=False),
        ),
    ]
