# Generated by Django 5.2.12 on 2026-05-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id_participante', models.AutoField(primary_key=True, serialize=False)),
                ('id_inscricao', models.IntegerField()),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('status_pagamento', models.CharField(max_length=20)),
                ('distrito', models.CharField(max_length=255)),
                ('igreja', models.CharField(max_length=255)),
                ('funcao', models.CharField(max_length=50)),
                ('pernoite', models.CharField(max_length=3)),
                ('comorbidade', models.CharField(max_length=3)),
                ('qual_comorbidade', models.CharField(blank=True, max_length=255)),
                ('no_plenario', models.BooleanField(default=False)),
            ],
        ),
    ]
