from django.core.management.base import BaseCommand
from enrollments.models import Distrito, Igreja

class Command(BaseCommand):
    help = 'Cadastra as igrejas no banco de dados'

    def handle(self, *args, **options):
        igrejas_data = [
            ('Alvorada', 'Agulhas Negras'),
            ('Cabral', 'Agulhas Negras'),
            ('Central de Itatiaia', 'Agulhas Negras'),
            ('Itatiaia', 'Agulhas Negras'),
            ('Morada do Contorno', 'Agulhas Negras'),
            ('Nova Alegria', 'Agulhas Negras'),
            ('Porto Real', 'Agulhas Negras'),
            ('Vila Pinheiro', 'Agulhas Negras'),
            ('Bangu', 'Bangu'),
            ('Gericinó', 'Bangu'),
            ('Jardim Novo', 'Bangu'),
            ('Marco Sete', 'Bangu'),
            ('Realengo', 'Bangu'),
            ('Senador Camará', 'Bangu'),
            ('Vila Kennedy', 'Bangu'),
            ('Vila Nova', 'Bangu'),
            ('Barra do Piraí', 'Barra do Piraí'),
            ('Ipiabas', 'Barra do Piraí'),
            ('Mendes', 'Barra do Piraí'),
            ('Morsing', 'Barra do Piraí'),
            ('Muqueca', 'Barra do Piraí'),
            ('Parapeuna', 'Barra do Piraí'),
            ('Parque Santana', 'Barra do Piraí'),
            ('Paulo de Frontin', 'Barra do Piraí'),
            ('Ponte do Rocha', 'Barra do Piraí'),
            ('Valença', 'Barra do Piraí'),
            ('Vassouras', 'Barra do Piraí'),
            ('1ª de Boa Vista', 'Barra Mansa'),
            ('2ª de Boa Vista', 'Barra Mansa'),
            ('Abelhas', 'Barra Mansa'),
            ('Ano Bom', 'Barra Mansa'),
            ('Ataulfo Paiva', 'Barra Mansa'),
            ('Cantagalo', 'Barra Mansa'),
            ('Colonia', 'Barra Mansa'),
            ('Jardim Primavera', 'Barra Mansa'),
            ('Monte Cristo', 'Barra Mansa'),
            ('Nova Esperança', 'Barra Mansa'),
            ('Piteiras', 'Barra Mansa'),
            ('Pontal do Paraíso', 'Barra Mansa'),
            ('Vila Independência', 'Barra Mansa'),
            ('Vila Maria', 'Barra Mansa'),
            ('Vista Alegre', 'Barra Mansa'),
            ('1ª de Campo Grande', 'Campo Grande'),
            ('2ª de Campo Grande', 'Campo Grande'),
            ('Abc', 'Campo Grande'),
            ('Betel', 'Campo Grande'),
            ('Cesarão', 'Campo Grande'),
            ('Cosmos', 'Campo Grande'),
            ('Jardim Maravilha', 'Campo Grande'),
            ('Jhon Wesley', 'Campo Grande'),
            ('Magarça', 'Campo Grande'),
            ('Mato Alto', 'Campo Grande'),
            ('Nova Sepetiba', 'Campo Grande'),
            ('Rio da Prata', 'Campo Grande'),
            ('Santa Cruz', 'Campo Grande'),
            ('Vila Jardim', 'Campo Grande'),
            ('1ª Angra dos Reis', 'Costa Verde'),
            ('2ª de Angra', 'Costa Verde'),
            ('Itaguai', 'Costa Verde'),
            ('Lidice', 'Costa Verde'),
            ('Frade', 'Costa Verde'),
            ('Mangaratiba', 'Costa Verde'),
            ('Muriqui', 'Costa Verde'),
            ('Parque Mambucaba', 'Costa Verde'),
            ('Cavalcante', 'Grajaú'),
            ('Centro do Rio', 'Grajaú'),
            ('Coelho Neto', 'Grajaú'),
            ('Engenho de Dentro', 'Grajaú'),
            ('Grajaú', 'Grajaú'),
            ('Irajá', 'Grajaú'),
            ('Olaria', 'Grajaú'),
            ('Pilares', 'Grajaú'),
            ('Rocha Miranda', 'Grajaú'),
            ('Santa Tereza', 'Grajaú'),
            ('Vieira Fazenda', 'Grajaú'),
            ('Anil', 'Jacarepaguá'),
            ('Barra da Tijuca', 'Jacarepaguá'),
            ('Curicica', 'Jacarepaguá'),
            ('Filadélfia', 'Jacarepaguá'),
            ('Gardênia Azul', 'Jacarepaguá'),
            ('Jardim Boiúna', 'Jacarepaguá'),
            ('Mananciais', 'Jacarepaguá'),
            ('Outeiro Santo', 'Jacarepaguá'),
            ('Praça Seca', 'Jacarepaguá'),
            ('Rocinha', 'Jacarepaguá'),
            ('Shangrilá', 'Jacarepaguá'),
            ('Vila Valqueire', 'Jacarepaguá'),
            ('Anjo da Guarda', 'Maranhão'),
            ('Caxias-Ma', 'Maranhão'),
            ('Cidade Operária', 'Maranhão'),
            ('Jota Lima', 'Maranhão'),
            ('Chatuba', 'Mesquita'),
            ('Delamare', 'Mesquita'),
            ('Edson Passos', 'Mesquita'),
            ('Juscelino', 'Mesquita'),
            ('Santo Amaro', 'Mesquita'),
            ('Santo Elias', 'Mesquita'),
            ('Vila Norma', 'Mesquita'),
            ('1ª de Nilópolis', 'Nilópolis'),
            ('2ª de Nilópolis', 'Nilópolis'),
            ('3ª de Nilópolis', 'Nilópolis'),
            ('4ª de Nilópolis', 'Nilópolis'),
            ('Alcobaça', 'Nilópolis'),
            ('Cabral', 'Nilópolis'),
            ('Costa Barros', 'Nilópolis'),
            ('Deodoro', 'Nilópolis'),
            ('Guadalupe', 'Nilópolis'),
            ('Nova Olinda', 'Nilópolis'),
            ('Olinda', 'Nilópolis'),
            ('Paiol', 'Nilópolis'),
            ('Parque Anchieta', 'Nilópolis'),
            ('R. de Albuquerque', 'Nilópolis'),
            ('1ª de Nova Iguaçu', 'Nova Iguaçu'),
            ('2ª de Nova Iguaçu', 'Nova Iguaçu'),
            ('3ª de Nova Iguaçu', 'Nova Iguaçu'),
            ('Cabuçu', 'Nova Iguaçu'),
            ('Caioaba', 'Nova Iguaçu'),
            ('Califórnia', 'Nova Iguaçu'),
            ('Caonze', 'Nova Iguaçu'),
            ('Heliópolis', 'Nova Iguaçu'),
            ('Jd. Belo Horizonte', 'Nova Iguaçu'),
            ('Nova América', 'Nova Iguaçu'),
            ('Santa Eugênia', 'Nova Iguaçu'),
            ('Xavante', 'Nova Iguaçu'),
            ('Arrozal', 'Piraí'),
            ('Califórnia', 'Piraí'),
            ('Nova Jerusalém', 'Piraí'),
            ('Palmeiras', 'Piraí'),
            ('Pinheiral', 'Piraí'),
            ('Piraí', 'Piraí'),
            ('Três Poços', 'Piraí'),
            ('Varjão', 'Piraí'),
            ('1ª de Austin', 'Queimados'),
            ('2ª de Austin', 'Queimados'),
            ('Cacuia', 'Queimados'),
            ('Cobrex', 'Queimados'),
            ('Coqueiros', 'Queimados'),
            ('Engenheiro Pedreira', 'Queimados'),
            ('Japeri', 'Queimados'),
            ('Jardim Excelso', 'Queimados'),
            ('Ponto Chic', 'Queimados'),
            ('Queimados', 'Queimados'),
            ('Açudes', 'Retiro'),
            ('Belmonte', 'Retiro'),
            ('Eldorado', 'Retiro'),
            ('Ebenezer', 'Retiro'),
            ('Retiro', 'Retiro'),
            ('Santa Cruz', 'Retiro'),
            ('São Luiz', 'Retiro'),
            ('Siderlândia', 'Retiro'),
            ('Vila Elmira', 'Retiro'),
            ('1º Santíssimo', 'Sta. Margarida'),
            ('2ª de Santíssimo', 'Sta. Margarida'),
            ('Inhoaíba', 'Sta. Margarida'),
            ('João Xxiii', 'Sta. Margarida'),
            ('Km 32', 'Sta. Margarida'),
            ('Santa Margarida', 'Sta. Margarida'),
            ('Areia Branca', 'São João de Meriti'),
            ('Belford Roxo', 'São João de Meriti'),
            ('Coelho da Rocha', 'São João de Meriti'),
            ('Éden', 'São João de Meriti'),
            ('Jardim América', 'São João de Meriti'),
            ('Jardim Bonifácio', 'São João de Meriti'),
            ('Jardim Redentor', 'São João de Meriti'),
            ('Parque São José', 'São João de Meriti'),
            ('Praça da Bandeira', 'São João de Meriti'),
            ('São João de Meriti', 'São João de Meriti'),
            ('Vila Humaitá', 'São João de Meriti'),
            ('Vila Jurandir', 'São João de Meriti'),
            ('Vila Tiradentes', 'São João de Meriti'),
            ('Vilar dos Teles', 'São João de Meriti'),
            ('Água Limpa', 'Volta Redonda'),
            ('Aterrado', 'Volta Redonda'),
            ('Casa de Pedra', 'Volta Redonda'),
            ('Jardim Redentor', 'Volta Redonda'),
            ('Minerlândia', 'Volta Redonda'),
            ('Monte Castelo', 'Volta Redonda'),
            ('Recanto do Sol', 'Volta Redonda'),
            ('Santo Agostinho', 'Volta Redonda'),
            ('São Lucas', 'Volta Redonda'),
            ('São Luiz da Barra', 'Volta Redonda'),
            ('Vila Americana', 'Volta Redonda'),
        ]

        criadas = 0
        existentes = 0
        erros = 0

        for nome_igreja, nome_distrito in igrejas_data:
            try:
                distrito = Distrito.objects.get(nome=nome_distrito)
                igreja, criado = Igreja.objects.get_or_create(nome=nome_igreja.strip(), distrito=distrito)

                if criado:
                    criadas += 1
                    self.stdout.write(f"✓ Criada: {nome_igreja} ({nome_distrito})")
                else:
                    existentes += 1
                    self.stdout.write(self.style.WARNING(f"- Já existia: {nome_igreja} ({nome_distrito})"))
            except Distrito.DoesNotExist:
                erros += 1
                self.stdout.write(self.style.ERROR(f"✗ Erro: Distrito '{nome_distrito}' não encontrado"))
            except Exception as e:
                erros += 1
                self.stdout.write(self.style.ERROR(f"✗ Erro ao criar {nome_igreja}: {str(e)}"))

        self.stdout.write(self.style.SUCCESS(f"\n--- Resumo ---"))
        self.stdout.write(self.style.SUCCESS(f"Criadas: {criadas}"))
        self.stdout.write(self.style.WARNING(f"Já existiam: {existentes}"))
        if erros:
            self.stdout.write(self.style.ERROR(f"Erros: {erros}"))
        self.stdout.write(self.style.SUCCESS(f"Total de igrejas: {Igreja.objects.count()}"))

## Command to execute: python3 manage.py cadastrar_igrejas
